permalink: /articles/:title

# Use the port config option to determine if we're in prod or dev
# anything other than port 80 is assumed to be dev
port: 80
url: //philipwalton.github.io/solved-by-flexbox

markdown: rdiscount
pygments: true

exclude:
- config.rb
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- bower.json
- bower_components
- LICENSE-GPL
- LICENSE-MIT

# Vendor Settings
google_analytics_tracking_id: UA-40829935-1
